### ISSUE TITLE
Query For Cloud Stack Management Server install

### ISSUE THREAD

**Issue by alamintech** [apache/cloudstack-primate#526] opened 2020-07-09 11:50 UTC
I have one query for my private cloud only LAN. Can I install  Cloud Stack Management Server access for my local LAN without public access.

How can I setup it. I am able to normally setup and access vm's using host as XEN server with include WAN Ethernet (public IP).

**Comment by rhtyd** [comment] 2020-07-10 07:53
Please ask questions on the users ML instead - http://cloudstack.apache.org/mailing-lists.html
You may also refer the docs and the quick install guide - http://docs.cloudstack.apache.org
Short answer - yes  @alamintech

Closing as this is not a bug or a feature request.

**Closed by rhtyd** 2020-07-10 07:53 UTC
Labels: testing

**Comment by alamintech** [comment] 2020-07-10 13:29
Thanks for your reply.
I got this link before but I am not understand which exact mail address. If possible please give me exact mail address where I send my query. 
 
Another Q. for you which part I will remove from [http://docs.cloudstack.apache.org/](url) this guide for my query. I am successfully install it using host as XEN server. 

Thanks!
