### ISSUE TITLE
[BUG] Domain admin cannot create a second user in an account

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack-primate#749] opened 2020-09-24 13:38 UTC
**Describe the bug**
both new and old UI fail but indifferent ways.

**To Reproduce**

1. Log in as a Domain Admin
1. Create a child domain to yours
1. Create a Domain admin account in the child domain
1. try to create a second user in the same account in the child domain

**Expected behavior**
the user should be created without problem.
* in primate an error is thrown
* in the old UI the child domain cannot be selected to create the user in

**Screenshots**
<img width="941" alt="image" src="https://user-images.githubusercontent.com/2486961/94151849-2990a800-fe7b-11ea-86d3-ead1944f5b21.png">

<img width="644" alt="Screenshot 2020-09-24 at 15 33 56" src="https://user-images.githubusercontent.com/2486961/94152043-6d83ad00-fe7b-11ea-9d4f-952badcf2ba0.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by ravening** [comment] 2020-09-25 15:35
@DaanHoogland I was not able to reproduce the issue

1. I have a domain "test" with account name "test" with "domain admin" access and username "test1"
2. Login to the domain admin account with "test1/test1/test" as username/password/domain
3. Now I create one more domain under test with name "test-11"
4. I create a new "domain admin" account with name "test-11-account" and first user with name "test-11-user" under domain "test-11"
5. Now I will try to create another user under account "test-11-account" with name "test-12-user"
6. Didnt see any error

**Comment by DaanHoogland** [comment] 2020-09-25 16:44
@ravening the error is when you create account but enter the same name as the original account. a bit of a strange use case but it is documented to work fine. So don't "+ Add User" but "+ Add Account". You see in the help of the account field of that dialog that it is supposed to work.

**Comment by ravening** [comment] 2020-09-25 21:14
> @ravening the error is when you create account but enter the same name as the original account. a bit of a strange use case but it is documented to work fine. So don't "+ Add User" but "+ Add Account". You see in the help of the account field of that dialog that it is supposed to work.

@DaanHoogland i didn't see add account option while adding second user

**Comment by utchoang** [comment] 2020-09-28 03:49
In my opinion, to solve the problem, the field account will be a selection for choosing accounts instead of input. @rhtyd What do you think?

**Comment by DaanHoogland** [comment] 2020-09-28 06:30
@utchoang that is not an option as users can also enter a non existing account name to create an account name different than the username

**Comment by utchoang** [comment] 2020-09-28 06:51
@DaanHoogland @rhtyd I mean, it will be both an option and an input field that allows creating an account?

**Comment by DaanHoogland** [comment] 2020-09-28 07:07
a combibox would be ok, i guess.

**Comment by utchoang** [comment] 2020-09-28 08:48
@rhtyd @davidjumani The problem, when I change the accounting field to a Combobox, is when I add an account with `accountid` selected, there is an error from the API that says` Internal error executing command, please contact your system administrator`. So is the API side not allowing add accounts in an existing account, right?
![image](https://user-images.githubusercontent.com/13766648/94410592-bac88d00-01a1-11eb-9c28-a063e2570ec5.png)
![image](https://user-images.githubusercontent.com/13766648/94410763-efd4df80-01a1-11eb-85ee-245a6f970b1f.png)
![image](https://user-images.githubusercontent.com/13766648/94410784-f6635700-01a1-11eb-8a80-261d562a14e8.png)

**Comment by rhtyd** [comment] 2020-09-28 10:55
cc @davidjumani @andrijapanicsb - any view on this?

**Comment by davidjumani** [comment] 2020-09-29 08:46
@DaanHoogland It looks like the backend checks whether the account exists even though it claims to just create a user if the account exists. Will create a fix for it

**Comment by davidjumani** [comment] 2020-09-29 08:47
@utchoang This will require a backend fix. I'll change the front end to a dropdown too while I'm at it. Thanks!

**Comment by rhtyd** [comment] 2020-09-29 09:07
The apidocs for `createAccount` says:
```
account                  string   Creates the user under the specified acco
                                  unt. If no account is specified, the use
                                  rname will be used as the account name.
```

So, this is correct if you're trying to create another account with the same, already existing user name. Instead to add user, you can go to the account -> view users and add user there.

**Comment by utchoang** [comment] 2020-09-29 09:12
@rhtyd If I using `accountid`, Can I create an account into an account?
![image](https://user-images.githubusercontent.com/13766648/94538707-8bcc1d00-026e-11eb-94dd-ed5d6bbe81f1.png)

**Comment by davidjumani** [comment] 2020-09-29 09:16
@rhtyd From my understanding, it'll just create a user in the specified account if passed, but while trying it, a new username in an existing account, I'm still getting the account exists error

**Comment by DaanHoogland** [comment] 2020-09-29 09:24
Let's check the old UI behaviour. I recall this passing (might have been in the API, not UI) For automation allowing to specify an existing account would be very useful, but i'm not hellbound on it. It is intuitive to just create users like this, so if we don't fix the code we must be more clear in the doc/hint.

**Comment by rhtyd** [comment] 2020-09-29 09:31
@utchoang that's not necessary, as @DaanHoogland comments the best thing would be to check the old UI and then this issue becomes a non-issue or a valid bug based on that.

**Comment by davidjumani** [comment] 2020-09-29 09:32
@DaanHoogland this fails via the old ui too, on trying to create an account (user) within an existing account via the createAccount command

![Screenshot from 2020-09-29 15-01-42](https://user-images.githubusercontent.com/8244774/94541001-b44f1980-0264-11eb-9135-051a2021d811.png)

**Comment by DaanHoogland** [comment] 2020-09-29 09:35
tnx @davidjumani, I think an edit of the hint text should do. ("account must not exist")

**Comment by rhtyd** [comment] 2020-09-29 12:03
Closing on the test remark, please reopen and move to 1.1 if you disagree @DaanHoogland

**Comment by DaanHoogland** [comment] 2020-09-29 12:40
I disagree, and this should be solved asap. It may only be a doc entry somewhere but it is very confusing that as the form starts with username a user would expect to be free to create any user that doesn't exist yet.

**Comment by rhtyd** [comment] 2020-09-29 15:35
@DaanHoogland I see it has been confirmed to be failing against  old UI as well, this is not a blocker as the form in Primate has same UX as the old UI. I've moved it to 1.1.

**Comment by davidjumani** [comment] 2020-09-30 04:42
@DaanHoogland Updated the doc at https://github.com/apache/cloudstack/pull/4354

**Comment by davidjumani** [comment] 2020-10-05 04:58
Closing as there is a fix in cloudstack

**Closed by davidjumani** 2020-10-05 04:58 UTC
Labels: bug
