### ISSUE TITLE
[BUG] After session expire the page reloads once more

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-primate#650] opened 2020-09-01 06:58 UTC
**Describe the bug**
When a session has expired, and the user refreshes the page, he's being displayed with the login screen. Right after that the page refreshes once more. 

**To Reproduce**

1. Leave a session to expire
2. Refresh the page
3. once loaded observe the page will refresh once more

**Expected behavior**
One refresh should be enough 

**Screenshots**
![reload](https://user-images.githubusercontent.com/13551960/91812378-a85a4280-ec39-11ea-94e1-7b186a002417.gif)

**Comment by davidjumani** [comment] 2020-09-02 05:30
Fixed in https://github.com/apache/cloudstack-primate/pull/658

**Comment by rhtyd** [comment] 2020-09-16 09:20
Can you test and close @borisstoyanov @andrijapanicsb

**Comment by DaanHoogland** [comment] 2020-09-22 07:39
double checking this with the latest nightly build. results in different environments seem erratic.

**Comment by DaanHoogland** [comment] 2020-09-22 08:40
@davidjumani I notice that after i perform anything on an expired session, it first redirects to the login page and then refreshes that page. Is this as intended? seems overkill (unless there is a good reason of course)

**Comment by rhtyd** [comment] 2020-09-22 12:03
@DaanHoogland if you've a form/wizard open for example and then you say restart management server, then you may redirect to login page with the form still open. I think that's why we reload, @davidjumani ?

**Comment by davidjumani** [comment] 2020-09-22 12:14
That's right @rhtyd  @DaanHoogland If it makes sense we can prevent the reload but if a popup form is submitted when the session expires, it will log out only when the user navigates to another page, but they will still be notified that their session has expired

**Comment by rhtyd** [comment] 2020-09-23 07:11
@davidjumani instead of change route and the do a reload, can't we just reload directly to the login page?

**Comment by davidjumani** [comment] 2020-09-23 08:24
If it's a direct reload, the notification that the session has expired won't popup (or will for half a second and then reload to the login page). I think it will be fine to not logout while the user has a popup form open , but just push the notification and redirect when the user navigates out

**Comment by rhtyd** [comment] 2020-09-23 12:10
@davidjumani a lot of apps redirect to login page and don't necessarily announce that the session has expired. One workaround is to show a modal with background blocked/hidden (like old UI) and you click okay which wiil reload to the login page. Thoughts?

**Comment by DaanHoogland** [comment] 2020-09-23 19:24
@rhtyd that would be very user friendly ;) an short display of an error, that disappears to quick to read is very disturbing.
btw, i don't think we should hold release for this, but it does need solving in the not to long term.

**Comment by davidjumani** [comment] 2020-09-24 07:33
@rhtyd Fixed the logout issue in https://github.com/apache/cloudstack-primate/pull/745 Now it logs out but leaves a notification that the session has expired

**Comment by DaanHoogland** [comment] 2020-09-25 12:49
verified with #745

**Closed by DaanHoogland** 2020-09-25 12:49 UTC
Labels: bug
