### ISSUE TITLE
[BUG] Negative Value in VM Metrics

### ISSUE THREAD

**Issue by hstan77** [apache/cloudstack-primate#914] opened 2021-01-07 04:12 UTC
**Describe the bug**

In UI, Compute -> Instances ,   click show metric,   the RAM column show Negative Value.

I have KVM hypervisor of 196G RAM,  only create one VM which is 1G RAM, and still show Negative Value.

Screen shoot as below:

[SREENSHOOT](https://demo.qdisk.io/index.php/s/KJmNrKSgxnzKRT8)

**To Reproduce**

1. Log in as a Admin
2. Go to 'compute" -> Instances 
3. Click on 'Metrics. at the top'
4. See the Negative Memory 

**Expected behavior**
Not a negative memory

**Screenshots**

**Desktop (please complete the following information):**
Tested on clodustack 4.14 and 4.15, primate

**Comment by davidjumani** [comment] 2021-01-07 04:33
Caused by https://github.com/apache/cloudstack/issues/4566

**Comment by utchoang** [comment] 2021-01-07 06:27
I think this issue from API response.

**Comment by rhtyd** [comment] 2021-01-18 12:01
Confirmed backend issue, https://github.com/apache/cloudstack/issues/4566 will fix the issue. Closing as it's not UI issue.

**Closed by rhtyd** 2021-01-18 12:01 UTC
Labels: bug
