### ISSUE TITLE
[BUG] Many screens show Account and Domain to non-root admins when they should not.

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-primate#475] opened 2020-06-30 16:17 UTC
**Describe the bug**

Many screens show Account and Domain to non-root admins when they should not.
In some cases it is purely superfluous (the user would know what account they were in)
In other cases (ie templates which can come from other accounts) it causes security data leakage.

**To Reproduce**

Log in as a non-admin user.
1. Go to one of the following screens:
Compute
- Kubernetes
- Instance Groups
- SSH Key Pairs
- Affinity Groups
Volumes
- Snapshots
- VM Snapshots
- Backups
Networks
- Guest Networks
- VPC
- Security Groups
- Public IP addresses
- VPN Customer Gateway
Images
- Templates
- ISOs
Projects

See that 'account' and or 'domain' are visible

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4810220/86149869-78d17180-baf4-11ea-826f-dbb5139b8e1d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

**Comment by rhtyd** [comment] 2020-07-01 02:21
@PaulAngus we also show the information in most screens (detail views if not list/table view) in legacy UI, ultimately the API response contains account and domain information for resources that a user is allowed to call/see.

Example screenshots from legacy UI, templates have the account/domain information:
![Screenshot from 2020-07-01 07-50-18](https://user-images.githubusercontent.com/95203/86195938-a90a2600-bb6f-11ea-9b64-0724a8d44fd6.png)

![Screenshot from 2020-07-01 07-48-12](https://user-images.githubusercontent.com/95203/86195936-a7d8f900-bb6f-11ea-88c3-90d2401d4261.png)

**Comment by rhtyd** [comment] 2020-07-01 02:45
With @PaulAngus - to review presented arguments and close the ticket; or start thread on dev/users ML to gather consensus on mitigation options such as:
- Hide account/domain information in Primate for the sections - template, iso, kubernetes iso and project
- Give some config parameter (Primate fix, provide via config.json) and/or global setting (CloudStack/server fix, fix API response) to show or hide this?

**Comment by PaulAngus** [comment] 2020-07-01 16:28
Agreed, **_most_** screens will display the user's own account and domain.  Therefore it's redundant data, so it's 'silly' to display it.

on the screens that **are** leaking data, not showing the data in the UI makes the problem 'less bad', but agreed, it is an API problem to start with.

**Comment by rhtyd** [comment] 2020-07-04 06:40
I checked in some cases we want to show account/domain to logged in users:
- In case of SAML users that are authorised across multiple accounts/domains (there's a  list and switch API)
- Edge case - In case of multiple users in an account who may have other users in other accounts

Let's show the silly redundant data like the silly old UI for now

**Comment by PaulAngus** [comment] 2020-07-04 07:00
A user can only be logged into one account at a time and therefore still one only see their own account and domain.  therefore we are still showing redundant data 

also it is offensive to close someone else's issue without their consent.

**Comment by rhtyd** [comment] 2020-07-04 07:19
@PaulAngus 
- The issue is subjective and I've advised already to start a discussion on dev/user ML
- Ultimately if the API response is fixed no changes in Primate will be required, you've agreed it's an API issue
- See my previous comments and http://cloudstack.apache.org/api/apidocs-4.14/apis/listAndSwitchSamlAccount.html, there are cases where a user may be allowed to switch between accounts/domains
- You've agreed its redundant data which is not a bug; for backward compatibility with legacy UI we should not remove data from UI 

As with any other reported issues, we close them when we have a PR merged or have established a resolution. In this case:
- It's not an UI issue leaking account/domain information
- The redundant data topic could be discussed on ML but it's not a bug

**Closed by rhtyd** 2020-07-04 07:19 UTC
Labels: Severity: Major, bug
