### ISSUE TITLE
[BUG] Unmanage VM leads to a 404 page

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-primate#782] opened 2020-10-01 09:41 UTC
**Describe the bug**
When you unmanage a VM, a 404 error (not found) page is shown.

**To Reproduce**

1. Log in as a User or an Admin
2. Go to 'Compute > Instances'
3. Click on an instance and then on the button 'Unmanage VM'

After the operation, the page is reloaded but the VM is no longer available which leads to 404 error page.

**Expected behavior**
Probably the user must be redirected back to the list of instances.

**Screenshots**
![image](https://user-images.githubusercontent.com/12384665/94793582-5c8aec80-03e3-11eb-9c1d-14b04d58f5cc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
None.

**Comment by rhtyd** [comment] 2020-10-01 10:12
@shwstppr can you check and advise?

**Comment by shwstppr** [comment] 2020-10-01 10:47
@rhtyd added a tentative fix which should resolve the issue. Will update after more testing

**Comment by DaanHoogland** [comment] 2020-10-01 10:52
there is an issue with 404 when destroying a VM as well (#753) , probably related (by looking from the outside in) did you consider this as a generic problem, yet @shwstppr ?

**Comment by shwstppr** [comment] 2020-10-01 11:29
@DaanHoogland not yet. I think the 404 bug for destroy VM got introduced with the custom componenent that has been added for `destroyVirtualMachine` API. Otherwise the code routes back to listview if the action icon is `delete`.
Unmanage VM has a different icon so I added a check for `unmanagedInstance` API in AutogenView.vue in my PR. Will test PR #761 for #753

**Comment by rhtyd** [comment] 2020-10-06 10:34
@vladimirpetrov please test latest master and close this. Thanks.

**Comment by rhtyd** [comment] 2020-10-12 10:03
I'm unable to reproduce, please re-open if you are @vladimirpetrov thanks.

**Closed by rhtyd** 2020-10-12 10:03 UTC
Labels: bug

**Comment by vladimirpetrov** [comment] 2020-10-12 13:17
I confirm, the bug is no longer present.
