### ISSUE TITLE
Template Filter dont work

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack-primate#536] opened 2020-07-13 15:42 UTC
I noticed that when creating a VM, the template filter feature doesnt work. I used the filter "is: public", but only the default centos 5 template shows up even though I have some public templates. I also tried this using a featured filter. is this a known bug?

**Comment by rhtyd** [comment] 2020-07-14 05:06
@gaaray2k that is not a supported feature, the templatefilter and isofilter parameter have fixed options that can be passed to the API.
I'm unable to reproduce the issue, on latest master we've now same UX as legacy UI where we show the four different template/iso filters like:

![Screenshot from 2020-07-14 10-34-09](https://user-images.githubusercontent.com/95203/87386258-b1298300-c5bd-11ea-822c-2057c77ee1c8.png)

Closing as this is not supported, thanks.

**Closed by rhtyd** 2020-07-14 05:06 UTC
Labels: bug
