### ISSUE TITLE
[BASIC NETWORK TESTING]  - Now start VM Zone Selection Bug

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#836] opened 2020-10-27 15:35 UTC
@weizhouapache @GabrielBrascher @wido - can those of you using Basic zone with SG, please test Primate against Basic Zone? Advanced zone stuff was extensively tested by many of us (me, Daan, etc) - so this would help if you could do it. Thanks

/ CC @rhtyd @PaulAngus

**Comment by DaanHoogland** [comment] 2020-11-16 12:08
@GabrielBrascher @wido @weizhouapache I tried to test https://github.com/apache/cloudstack/issues/4158 but got stopped in my tracks because of below issue, not sure if it is still a problem but it is for 4.14:
<img width="1427" alt="Screenshot 2020-11-16 at 12 51 54" src="https://user-images.githubusercontent.com/2486961/99250811-8fab0300-280c-11eb-99c2-66b0e304c6fa.png">

**Comment by andrijapanicsb** [comment] 2020-11-16 12:10
cc @nvazquez as I think he could advise about that one ^^^

**Comment by slavkap** [comment] 2020-11-16 15:02
Hi @andrijapanicsb ! I'm not sure that my comment is for here, but I tried to deploy VM with the new UI with Basic zone. I'm prompt to provide a network

![image](https://user-images.githubusercontent.com/51903378/99266901-f7247b00-282b-11eb-8aaa-ce8e8c35d222.png)

 and when I mark the default one 

![image](https://user-images.githubusercontent.com/51903378/99267898-32737980-282d-11eb-941d-efb7353918a8.png)


`http://localhost:5050/client/api/?zoneid=307c2b69-86eb-451e-8517-6113c59648c4  templateid=1118f7ab-fc15-11ea-a978-02000a02019c  serviceofferingid=561efdff-a07d-4676-beb0-0f2025faa20c  affinitygroupids=  iptonetworklist[0].networkid=4e59f45b-d645-4b7b-88ce-7d32c4b958e1  iptonetworklist[0].mac=aa:aa:aa:aa:aa:aa  securitygroupids=42d3aa52-fc15-11ea-a978-02000a02019c  command=deployVirtualMachine `


In the old UI the network is marked by default but the parameter isn't send:

`command=deployVirtualMachine  response=json  zoneid=307c2b69-86eb-451e-8517-6113c59648c4  templateid=1118f7ab-fc15-11ea-a978-02000a02019c  hypervisor=KVM  rootdisksize=8  serviceofferingid=561efdff-a07d-4676-beb0-0f2025faa20c  securitygroupids=42d3aa52-fc15-11ea-a978-02000a02019c`

**Comment by PaulAngus** [comment] 2020-11-16 16:00
@andrijapanicsb @DaanHoogland the new UI is only GA with 4.15.
Functions may or may not work with pre-GA versions, but they that's not something we should concern ourselves with now.

Also, registering templates in 4.14 with new UI is not related to this Basic Networking testing _issue_. Can I ask that this thread does not continue here.  In fact, my preference would be that the whole tangential thread is deleted completely to stop confusion.

**Comment by PaulAngus** [comment] 2020-11-16 16:05
@slavkap Thank you for your help. Could you test the VM deployment against the master branch please.  The new UI will only go GA against 4.15.  I suspect that you'll get the same result, but it'll give us a slightly better starting point.

If you wouldn't mind, it would be very helpful if you could use the browser dev tools, to compare the API call made by the old UI to the one sent by the new UI.

**Comment by PaulAngus** [comment] 2020-11-16 16:11
@slavkap when you deployed the VM in the new UI, did you set the rootdisksize to 8 or has the new UI added it itself?

+ I can only see pain by the UI sending a blank affinitygroupids parameter.

**Comment by PaulAngus** [comment] 2020-11-16 16:23
@davidjumani could you have a look at the extra **_networkid_**, and **_affinitygroupids_**, and _**mac**_ and _**rootdisksize**_ which are being sent when they haven't been set in the UI please.  **_networkid_** is breaking VM deployment in basic zones.  The others will likely break something at some time.

**Comment by slavkap** [comment] 2020-11-16 16:33
@PaulAngus the problem still appears on master. In my previous comment the API calls are copied from dev tools. Also in the new UI I didn't provide rootdisksize because there is only option the override it. 

Here are the screenshots from new and old UIs with the API calls:

![image](https://user-images.githubusercontent.com/51903378/99280056-99972b00-2839-11eb-8039-11d6e35b817a.png)

`http://localhost:5050/client/api/?zoneid=45b4a203-d00e-4e54-b1a8-d7648d2db436&templateid=582131ee-1f50-11eb-ae69-02000a0201ba&serviceofferingid=8b25c596-bdc5-4681-9f3b-6fa3ab998f75&affinitygroupids=&iptonetworklist[0].networkid=dcd06f91-cba0-400d-9e67-644e7419f23c&securitygroupids=9c1ba671-1f51-11eb-ae69-02000a0201ba&command=deployVirtualMachine&response=json`

and old UI

![image](https://user-images.githubusercontent.com/51903378/99280177-b92e5380-2839-11eb-8440-5a97d9750d3b.png)


`http://localhost:8080/client/api?command=deployVirtualMachine&response=json&zoneid=45b4a203-d00e-4e54-b1a8-d7648d2db436&templateid=582131ee-1f50-11eb-ae69-02000a0201ba&hypervisor=KVM&rootdisksize=8&serviceofferingid=8b25c596-bdc5-4681-9f3b-6fa3ab998f75&securitygroupids=9c1ba671-1f51-11eb-ae69-02000a0201ba&boottype=BIOS&bootmode=LEGACY&_=1605543657690`

**Comment by slavkap** [comment] 2020-11-17 08:04
@PaulAngus  I think that there was a misunderstanding. In m first comment there are two API calls from the new and the old UIs. The first API call is from the new UI (primate) and I have tested with and without mac (first I thought that it's mandatory). And I didn't set rootdisksize because there is only an option to override and I guess that when deploying VM it will get the template size. The second API call is from the old UI and there is rootdisksize provided.

I have tested it now again and  at runtime I set the networkids to null and the request didn't fail in the further execution - the VM was deployed correctly.

**Comment by PaulAngus** [comment] 2020-11-18 09:21
Hi @slavkap - the first bit of confusion was might fault, I realised that you'd included the browser output after I'd pressed send.


If you had to explicitly set the network values to NULL, then from a defensive programming point of view and a 'let's not confuse the user' point of view;  The choice of network, shouldn't be visible to the user when the zone uses basic networking?

**Comment by davidjumani** [comment] 2020-11-18 11:40
@PaulAngus @slavkap Created a fix for this https://github.com/apache/cloudstack-primate/pull/864

**Comment by rhtyd** [comment] 2020-12-03 09:05
@slavkap @weizhouapache @GabrielBrascher @wido - any further update on running tests with basic zone/networking against latest master? Thanks.

**Comment by slavkap** [comment] 2020-12-03 16:43
Hi @rhtyd  I've just tried simple scenarios - to deploy vm, create template from snapshot and deploy vm from it. If you can help me with scenarios for basic network I could test it.
I found another "problem" but it's not related to the basic zone I guess. When I want to start a VM in the new UI I have option to choose zone,pod,cluster and host which are not related to the VM's zone. In the old UI when I want to start it I have option only to choose configurations from its zone.

Here is a screenshots for what I mean

Old UI the pod,clusters or hosts are listed by the zone id of the VM

![Screenshot from 2020-12-03 18-03-30](https://user-images.githubusercontent.com/51903378/101059038-82c13a00-3596-11eb-865a-e173c3252fdd.png)


From new UI are listed all pods, clusters or hosts without any constrains 
![image](https://user-images.githubusercontent.com/51903378/101059008-776e0e80-3596-11eb-97d1-cb964e6a88db.png)

Do I have to delete this comment from here and open a new issue (or this is expected behaviour)?

**Comment by rhtyd** [comment] 2020-12-05 15:25
Tested and merged the PR, pl test and close the PR @andrijapanicsb  cc @slavkap

**Comment by slavkap** [comment] 2020-12-07 07:04
@rhtyd I've tested with the fix and it's work correct

**Comment by rhtyd** [comment] 2020-12-07 09:30
Thanks @slavkap closing on your remark.

**Closed by rhtyd** 2020-12-07 09:30 UTC
Labels: Severity: Blocker, bug
