### ISSUE TITLE
[BUG] Incorrect user name shown in top right corner

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-primate#249] opened 2020-03-23 13:43 UTC
**Describe the bug**
When multiple users are attached to a an account, the full name of the first user on the account is shown instead of the user's own name. 

**To Reproduce**
1. Create a new account
2. Attach two users to this account, set their full names as User1 and User2
3. Log in as User2
4. See User1 in the top right corner (or vice-versa)

**Expected behavior**
The user's full name is displayed, independent of the account.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: N/A

**Additional context**
It's not 100% clear if this issue might be related to LDAP. We authenticate users via LDAP, but all users are duplicated in CloudStack to assign them to different accounts. The LDAP records are correct.

**Comment by rhtyd** [comment] 2020-03-23 17:11
@onitake can you debug using chrome dev-tools if after log in listUsers API is called? I'll try to reproduce this but I don't have a ready to test against LDAP setup yet.

**Comment by onitake** [comment] 2020-03-23 17:31
Yes, I get a call to listUsers.

The API calls on login are as follows:
1. login
2. listApis
3. listUsers

The listUsers call returns a list of all users on the account, and the user name displayed on the top right is precisely the first user returned.

It looks like this isn't even related to LDAP.

**Comment by rhtyd** [comment] 2020-03-25 11:10
@onitake I've put in a workaround fix, can you test latest master and reopen if you're still able to reproduce it?

**Comment by onitake** [comment] 2020-03-25 13:40
I'm slightly confused - that commit removes a random welcome message in Chinese?
How does it relate to the user displayed in the top menu?

In any case, it doesn't seem to fix the problem...

**Comment by onitake** [comment] 2020-03-25 13:44
FYI, I don't have permission to reopen the ticket.

**Comment by onitake** [comment] 2020-03-25 14:08
Another thing: It looks like the top right menu display links around the account, not the user. I'm not sure how useful this is.

IMHO, it would make more sense to put a link to the user's settings there, since it's also the right place to edit your data and fetch your API key.

**Comment by rhtyd** [comment] 2020-03-26 09:13
@onitake the profile/setting would go to a logged in user's profile. Can you check latest master?

**Comment by onitake** [comment] 2020-03-26 17:51
Sorry, that didn't improve anything.
I still get the name of the account's first user instead of my own.

The profile link goes to the user profile now, but it's the account's first user's profile, not my own.
So, it's an improvement IMHO, but still not quite what it should be.

**Comment by rhtyd** [comment] 2020-05-04 10:34
@vladimirpetrov  cc @borisstoyanov can you look into this and see if you can reproduce it. I cannot.

**Comment by vladimirpetrov** [comment] 2020-05-07 15:16
I cannot reproduce this issue using the latest master build (0.4.0-20200507). It seems to be working as expected.

**Comment by rhtyd** [comment] 2020-05-08 12:03
Unable to reproduce, closing on this remark. Let's revisit this after tech preview.

**Closed by rhtyd** 2020-05-08 12:03 UTC
Labels: bug

**Comment by onitake** [comment] 2020-05-08 13:44
If you can't reproduce it, then it might in fact be related to LDAP account association.

I can reproduce it in our environment every time. The LDAP user I logged in as is simply "lost" after login, and I only see the account's name and profile link.
