### ISSUE TITLE
[BUG] Issue with templateFilter=all for a normal USER role

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-primate#605] opened 2020-08-21 16:40 UTC
Logged in as a normal user role.

![image](https://user-images.githubusercontent.com/45762285/90913942-4c8fee00-e3dd-11ea-8ce4-2049e5561be7.png)

This happened right after I choose a Zone (and, since a single zone, why wouldn't it be auto-populated???)
http://10.10.3.233:8080/client/api/?templateFilter=all&id=0ef7f0ac-7476-47db-a0f8-ea1f2883c60f&details=all&command=listTemplates&response=json

the guilty ione: templateFilter=all

**Comment by davidjumani** [comment] 2020-08-24 07:26
Looks like a regression caused in a prior commit. Will fix it along with the vapps fix

**Comment by andrijapanicsb** [comment] 2020-08-27 08:55
note to myslef :) - need to test PR609

**Comment by davidjumani** [comment] 2020-08-28 08:39
@andrijapanicsb Fixed in #609 Could you verify the same ?

**Comment by rhtyd** [comment] 2020-08-28 08:44
@davidjumani if we're not sure when #609 will merge, can you send another PR that fixes this blocker for the specific case for VM deployment for users?

**Comment by rhtyd** [comment] 2020-08-28 09:55
@andrijapanicsb please reopen if you can again reproduce it with latest master, thnx

**Closed** 2020-08-28 09:54 UTC
Labels: bug

**Comment by andrijapanicsb** [comment] 2020-08-28 11:03
LGTM
