### ISSUE TITLE
a few issues.

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack-primate#566] opened 2020-07-29 11:24 UTC
1) When using a public IP, I have three features I can use. LB, PF or firewall. But only one feature can be use at a time. If I use the LB feature for example, shouldn't the others be grayed out so users cant use them? Right now all the options are available and you get some internal error message but if you look at the logs it says that error is because you have another feature enabled.

2) I disabled the redundant vpc service offering but still shows up when creating a vpc in primate. it doesnt show up in the legacy UI.

3) under VPC -> networks. ACL name shows the ACL GUID/UUID. it should be the acl name

**Comment by davidjumani** [comment] 2020-08-05 11:12
@gaaray2k 
1. Right now primate follows the same functionality of the legacy UI in which you can still use other features of an IP
2. It's been fixed in #564 
3. It's a backend issue, would need to change the API response to include the ACL Name

**Comment by gaaray2k** [comment] 2020-08-05 11:23
For #1 I am sure once you enable a feature, the other ones are unclickable. I could be wrong.

**Comment by rhtyd** [comment] 2020-08-06 09:59
@gaaray2k can you provide reproduction steps against old UI and Primate?

**Comment by rhtyd** [comment] 2020-08-11 09:09
Ping @gaaray2k - we're unable to reproduce any issues wrt #1 - if you're unable to provide steps to reproduce issue, then can we close this?

**Comment by gaaray2k** [comment] 2020-08-11 10:50
I'll do this today

**Closed** 2020-08-11 18:18 UTC
Labels: bug
